In [22]:
import numpy as np

In [23]:
arr = np.ones((3,4))

In [24]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [25]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [26]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [27]:
np.empty((3,4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [28]:
np.eye(5)#it always give a square matrix n*n matrix,2D dimentional Matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(2)#to calculate a inverse matrix

array([[1., 0.],
       [0., 1.]])

In [31]:
np.eye(2,dtype=int)

array([[1, 0],
       [0, 1]])

In [32]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
#optional
import pandas as pd
pd.DataFrame(arr)

0    1    2    3
0  1.0  1.0  1.0  1.0
1  1.0  1.0  1.0  1.0
2  1.0  1.0  1.0  1.0

In [34]:
#extra topic
import random as rd
rd.choice((1,2,3,4,5,6))

4

In [35]:
rd.choice("Lalit")

'a'

In [36]:
rd.randrange(1,100)

25

In [37]:
rd.random()#a random no is generated between 0 and 1/ 0 is included 1 is excluded.

0.5503636431847129

In [38]:
list1=[1,2,3,4,5]
rd.shuffle(list1)

In [39]:
list1

[5, 1, 4, 2, 3]

In [40]:
rd.uniform(7,14)#a no between 7 and 14 

10.948675072150676

In [1]:
=============================================================================================================

In [42]:
np.random.rand(1)

array([0.2081526])

In [43]:
np.random.rand(2,3)

array([[0.68563826, 0.94313707, 0.69112741],
       [0.92024179, 0.23173888, 0.52494386]])

In [44]:
np.random.rand(2,3)

array([[0.63670352, 0.04392961, 0.61822641],
       [0.42917224, 0.68396247, 0.44268309]])

In [45]:
np.random.random_sample(1)

array([0.48858486])

In [46]:
np.random.randint(1,5,size = (3,4))#gives the array in the range of 1,5 of size 3 rows and 4 columns

array([[4, 1, 4, 2],
       [1, 1, 2, 4],
       [3, 1, 2, 3]])

In [47]:
arr1 = np.random.randint(1,5,size = (3,4))

In [48]:
arr1

array([[2, 3, 4, 4],
       [2, 3, 2, 2],
       [3, 3, 2, 4]])

In [49]:
arr.size

12

In [50]:
arr.shape

(3, 4)

In [51]:
arr.ndim

2

In [52]:
arr1

array([[2, 3, 4, 4],
       [2, 3, 2, 2],
       [3, 3, 2, 4]])

In [53]:
arr1.reshape(2,6)

array([[2, 3, 4, 4, 2, 3],
       [2, 2, 3, 3, 2, 4]])

In [54]:
arr1.reshape(2,1)#reshape param are multiple of total size 

ValueError: cannot reshape array of size 12 into shape (2,1)

In [ ]:
arr1.reshape(6,2)

In [55]:
arr1.reshape(12,1)

array([[2],
       [3],
       [4],
       [4],
       [2],
       [3],
       [2],
       [2],
       [3],
       [3],
       [2],
       [4]])

In [56]:
arr1.reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [57]:
arr1.reshape(4,-11)#put any negative value

array([[2, 3, 4],
       [4, 2, 3],
       [2, 2, 3],
       [3, 2, 4]])

In [58]:
arr1.reshape(3,-100)

array([[2, 3, 4, 4],
       [2, 3, 2, 2],
       [3, 3, 2, 4]])

In [59]:
arr1.reshape(-1,4)

array([[2, 3, 4, 4],
       [2, 3, 2, 2],
       [3, 3, 2, 4]])

In [60]:
arr1.reshape(-1,3)#at least we know any dimention

array([[2, 3, 4],
       [4, 2, 3],
       [2, 2, 3],
       [3, 2, 4]])

In [61]:
arr1.reshape(3,4).base

array([[2, 3, 4, 4],
       [2, 3, 2, 2],
       [3, 3, 2, 4]])

In [62]:
arr1

array([[2, 3, 4, 4],
       [2, 3, 2, 2],
       [3, 3, 2, 4]])

In [63]:
arr1.reshape(12).base

array([[2, 3, 4, 4],
       [2, 3, 2, 2],
       [3, 3, 2, 4]])

In [64]:
arr.reshape(12,).base

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [65]:
arr1

array([[2, 3, 4, 4],
       [2, 3, 2, 2],
       [3, 3, 2, 4]])

In [66]:
arr1.size

12

In [67]:
arr1.reshape(2,2,3)#2 rows and 3 cols repeated 2 times

array([[[2, 3, 4],
        [4, 2, 3]],

       [[2, 2, 3],
        [3, 2, 4]]])

In [68]:
arr1.reshape(3,2,2)

array([[[2, 3],
        [4, 4]],

       [[2, 3],
        [2, 2]],

       [[3, 3],
        [2, 4]]])

In [69]:
arr1.reshape(2,3,2)

array([[[2, 3],
        [4, 4],
        [2, 3]],

       [[2, 2],
        [3, 3],
        [2, 4]]])

In [70]:
arr1.reshape(1,2,2,3)

array([[[[2, 3, 4],
         [4, 2, 3]],

        [[2, 2, 3],
         [3, 2, 4]]]])

In [71]:
arr1.reshape(4,3,1)#3 rows and 1 cols repeated 4 times

array([[[2],
        [3],
        [4]],

       [[4],
        [2],
        [3]],

       [[2],
        [2],
        [3]],

       [[3],
        [2],
        [4]]])

In [72]:
arr.reshape(1,1,1,1,1,1,2,2,3)

array([[[[[[[[[1., 1., 1.],
              [1., 1., 1.]],

             [[1., 1., 1.],
              [1., 1., 1.]]]]]]]]])

In [73]:
#check dimention
list1=[1,2,3,4]
arr = np.array(list1)

In [74]:
arr

array([1, 2, 3, 4])

In [75]:
arr.ndim

1

In [76]:
arr2 = np.array([[2,3],[4,5]])
arr2

array([[2, 3],
       [4, 5]])

In [77]:
arr2.ndim

2

In [78]:
arr2 = np.zeros((3,4))


In [79]:
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
arr2.ndim

2

In [81]:
arr3 = np.zeros((1,3,4)) #3 rows, 4 colums -->> 2d array + 1d

In [82]:
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [83]:
arr3.ndim

3

In [84]:
arr3.shape

(1, 3, 4)

In [85]:
arr4=np.zeros((1,1,3,4)) #3 rows , 4 cols -->>2d arayy +1d + 1d

In [86]:
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [87]:
arr4.shape

(1, 1, 3, 4)

In [88]:
arr4.ndim

4

In [89]:
arr5=np.zeros((1,3,4))
arr5

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [90]:
arr5.ndim

3

In [91]:
arr3.shape

(1, 3, 4)

In [92]:
arr6=np.zeros((2,3,4))#3 rows and 4 cols repeated 2twice

In [93]:
arr6

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [94]:
arr6.shape

(2, 3, 4)

In [95]:
arr7=np.zeros((3,3,4))#3 rows and 4 cols repeated 3 times

In [96]:
arr7

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [97]:
arr7.shape

(3, 3, 4)

In [98]:
arr7.ndim

3

In [99]:
arr7.size

36

In [100]:
arr1=np.random.randint(1,10,(5,6))#values between 1 to 10 5 rows and 6 cols

In [101]:
arr1

array([[1, 3, 7, 3, 1, 4],
       [3, 8, 6, 5, 4, 3],
       [4, 6, 1, 9, 5, 3],
       [9, 9, 1, 3, 6, 3],
       [3, 7, 6, 4, 6, 4]])

In [102]:
arr1>5

array([[False, False,  True, False, False, False],
       [False,  True,  True, False, False, False],
       [False,  True, False,  True, False, False],
       [ True,  True, False, False,  True, False],
       [False,  True,  True, False,  True, False]])

In [103]:
arr1[arr1>5]#****Imp****:-

array([7, 8, 6, 6, 9, 9, 9, 6, 7, 6, 6])

In [104]:
arr1[arr1<5]

array([1, 3, 3, 1, 4, 3, 4, 3, 4, 1, 3, 1, 3, 3, 3, 4, 4])

In [105]:
arr1

array([[1, 3, 7, 3, 1, 4],
       [3, 8, 6, 5, 4, 3],
       [4, 6, 1, 9, 5, 3],
       [9, 9, 1, 3, 6, 3],
       [3, 7, 6, 4, 6, 4]])

In [106]:
arr

array([1, 2, 3, 4])

In [107]:
arr[0]

1

In [108]:
arr[-1]

4

In [109]:
arr1

array([[1, 3, 7, 3, 1, 4],
       [3, 8, 6, 5, 4, 3],
       [4, 6, 1, 9, 5, 3],
       [9, 9, 1, 3, 6, 3],
       [3, 7, 6, 4, 6, 4]])

In [110]:
arr1[0][1:4]

array([3, 7, 3])

In [111]:
arr1[0]

array([1, 3, 7, 3, 1, 4])

In [112]:
arr1[0][0]

1

In [113]:
arr1[-1][-1]

4

In [114]:
#arr1[0,[1,3]]
arr1[0][2:4]

array([7, 3])

In [115]:
arr1[2:4,[2,3]]

array([[1, 9],
       [1, 3]])

In [116]:
arr1[2:4,[0,2]]

array([[4, 1],
       [9, 1]])

In [117]:
arr1

array([[1, 3, 7, 3, 1, 4],
       [3, 8, 6, 5, 4, 3],
       [4, 6, 1, 9, 5, 3],
       [9, 9, 1, 3, 6, 3],
       [3, 7, 6, 4, 6, 4]])

In [118]:
arr1[2:5]

array([[4, 6, 1, 9, 5, 3],
       [9, 9, 1, 3, 6, 3],
       [3, 7, 6, 4, 6, 4]])

In [119]:
arr1[2:5,[0,2]]

array([[4, 1],
       [9, 1],
       [3, 6]])

In [120]:
arr1[2:5,0:2]#Slicing

array([[4, 6],
       [9, 9],
       [3, 7]])

In [121]:
arr1[2:4]

array([[4, 6, 1, 9, 5, 3],
       [9, 9, 1, 3, 6, 3]])

In [122]:
arr1[2:5,[0,1,2]]

array([[4, 6, 1],
       [9, 9, 1],
       [3, 7, 6]])

In [123]:
arr1[[2,4],[0,2]]

array([4, 6])

In [124]:
arr1

array([[1, 3, 7, 3, 1, 4],
       [3, 8, 6, 5, 4, 3],
       [4, 6, 1, 9, 5, 3],
       [9, 9, 1, 3, 6, 3],
       [3, 7, 6, 4, 6, 4]])

In [125]:
arr1[[2,4]]#selecting specific column

array([[4, 6, 1, 9, 5, 3],
       [3, 7, 6, 4, 6, 4]])

In [126]:
arr1[[2,4],[0,2]]#here ge get from 2nd row 0th element and from 4rth row 2nd element

array([4, 6])

In [127]:
arr1[[2,4],0:3]

array([[4, 6, 1],
       [3, 7, 6]])

In [128]:
arr1

array([[1, 3, 7, 3, 1, 4],
       [3, 8, 6, 5, 4, 3],
       [4, 6, 1, 9, 5, 3],
       [9, 9, 1, 3, 6, 3],
       [3, 7, 6, 4, 6, 4]])

In [129]:
arr1[2:4, [1,3]]

array([[6, 9],
       [9, 3]])

In [130]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [131]:
arr1

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [132]:
arr2

array([[1, 1, 2],
       [1, 1, 1],
       [1, 2, 2]])

In [133]:
arr1+arr2

array([[2, 2, 3],
       [3, 2, 2],
       [3, 4, 4]])

In [134]:
arr1-arr2

array([[ 0,  0, -1],
       [ 1,  0,  0],
       [ 1,  0,  0]])

In [135]:
arr1*arr2

array([[1, 1, 2],
       [2, 1, 1],
       [2, 4, 4]])

In [136]:
arr1 @ arr2#matrix multiplication or dot product

array([[ 3,  4,  5],
       [ 4,  5,  7],
       [ 6,  8, 10]])

In [137]:
arr1/arr2

array([[1. , 1. , 0.5],
       [2. , 1. , 1. ],
       [2. , 1. , 1. ]])

In [138]:
arr/0

C:\Users\boras\AppData\Local\Temp\ipykernel_16592\4291252909.py:1: RuntimeWarning: divide by zero encountered in divide
  arr/0


array([inf, inf, inf, inf])

In [139]:
#Broad Casting

In [140]:
arr = np.zeros((3,4))

In [141]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [142]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [143]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [144]:
a=np.array([1,2,3,4])

In [145]:
a

array([1, 2, 3, 4])

In [146]:
arr + a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [147]:
b=np.array([1,2,3])

In [148]:
b

array([1, 2, 3])

In [149]:
arr + b

ValueError: operands could not be broadcast together with shapes (3,4) (3,) 

In [150]:
b=np.array([[1,2,3]])#convert the array into the 2D then we add in the array

In [151]:
b

array([[1, 2, 3]])

In [152]:
b.T

array([[1],
       [2],
       [3]])

In [153]:
arr + b.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [154]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.        ],
       [1.41421356, 1.        , 1.        ],
       [1.41421356, 1.41421356, 1.41421356]])

In [155]:
np.log10(arr1)

array([[0.     , 0.     , 0.     ],
       [0.30103, 0.     , 0.     ],
       [0.30103, 0.30103, 0.30103]])

In [156]:
np.exp(arr1)

array([[2.71828183, 2.71828183, 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183],
       [7.3890561 , 7.3890561 , 7.3890561 ]])

In [157]:
a

array([1, 2, 3, 4])

In [158]:
np.min(a)

1

In [159]:
arr1

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [160]:
np.min(arr1)

1

In [161]:
np.max(arr1)

2

In [162]:
arr1

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [163]:
arr1.T

array([[1, 2, 2],
       [1, 1, 2],
       [1, 1, 2]])

In [166]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [167]:
arr1

array([[1, 1, 1],
       [2, 1, 1],
       [2, 2, 2]])

In [168]:
arr1.flatten()#reduce higher Dimention to Single Dimention

array([1, 1, 1, 2, 1, 1, 2, 2, 2])

In [169]:
#expend dimension-->This fun expands the array by inserting new axis
arr=np.array([[1,2,3],[4,5,6]])

In [170]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
np.sum(arr)

21

In [173]:
arr=np.array([[1,2,3],[4,5,6],[1,2,3]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [174]:
np.sum(arr)

27

In [175]:
np.sum(arr,axis=0)

array([ 6,  9, 12])

In [176]:
np.sum(arr,axis=1)

array([ 6, 15,  6])

In [177]:
#expend dimention of the array
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [178]:
arr.ndim

1

In [180]:
arr1=np.expand_dims(arr,axis=0)

In [181]:
arr1

array([[1, 2, 3, 4]])

In [182]:
arr1.ndim

2

In [188]:
arr2=np.expand_dims(arr1,axis = 0)
arr2

array([[[1, 2, 3, 4]]])

In [189]:
arr2.shape

(1, 1, 4)

In [190]:
arr2.ndim

3

In [191]:
arr3=np.expand_dims(arr2,axis=1)
arr3

array([[[[1, 2, 3, 4]]]])

In [192]:
arr3.shape

(1, 1, 1, 4)

In [193]:
arr3.ndim

4

In [194]:
arr

array([1, 2, 3, 4])

In [195]:
arr1=np.expand_dims(arr,axis=1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [196]:
arr1.shape

(4, 1)

In [197]:
arr.ndim

1

In [206]:
arr = np.zeros((3,4),int)
arr

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [207]:
arr.ndim

2

In [208]:
arr1=np.expand_dims(arr,axis=0)
arr1

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [209]:
arr1.ndim

3

In [210]:
arr1=np.expand_dims(arr,axis=1)#col wise dimention was change
arr1

array([[[0, 0, 0, 0]],

       [[0, 0, 0, 0]],

       [[0, 0, 0, 0]]])