In [ ]:
#Numpy-Numerical Python-Use in data analysis-Travis Oliphant-2005-Bell's labrotory-Numpy is bulit on cpp-it's 
#fasterst execution language-Numpy is Fast because it basic function array

In [4]:
import numpy as np

In [5]:
np.__version__

'1.24.3'

In [7]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [ ]:
#Why numpy
#Mathematical function
#Faster than otherr data structure
#

In [9]:
l=[1,2,3,4,5] #it is data structure to store the hetrogeneous data 

In [14]:
arr=np.array(l)

In [15]:
type(np.array(l))

numpy.ndarray

In [12]:
l=np.array(l)

In [13]:
print(l,type(l))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
#ndarray means -n Dimentional array
#Array-array is the way numpy store the data it stores the same type of data,Store the homogeneous data only

In [16]:
arr.ndim

1

In [17]:
l=[1,2,3,4,5,"Lalit"]
arr1=np.array(l)
arr1

array(['1', '2', '3', '4', '5', 'Lalit'], dtype='<U11')

In [19]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [20]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
arr1.ndim

2

In [22]:
l=[1,2,3,4]

In [23]:
np.array(l)

array([1, 2, 3, 4])

In [24]:
np.matrix(l)#matrix will be by default 2D

matrix([[1, 2, 3, 4]])

In [25]:
np.matrix([[[1,2],[5,6],[7,8]]])

ValueError: matrix must be 2-dimensional

In [26]:
np.array([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [27]:
#more way to convert to array
#np.array ans np.asarray are same there is no difference
np.asarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [ ]:
#Matrix is a subclass of array

In [28]:
np.asanyarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [29]:
mat = np.matrix(l)

In [30]:
mat

matrix([[1, 2, 3, 4]])

In [31]:
np.asanyarray(mat)#Converted into matrix but not in array

matrix([[1, 2, 3, 4]])

In [ ]:
#Convert the input to an ndarray,but pass ndarray subclasses

In [32]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [33]:
np.asarray([[[1,2],[5,6],[7,8]]])

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [34]:
np.array(([[[1,2],[5,6],[7,8]]]))

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [35]:
np.asanyarray(([[[1,2],[5,6],[7,8]]]))

array([[[1, 2],
        [5, 6],
        [7, 8]]])

In [36]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4]])

In [37]:
np.asarray(mat)

array([[1, 2, 3, 4]])

In [38]:
np.array(mat)

array([[1, 2, 3, 4]])

In [39]:
mat

matrix([[1, 2, 3, 4]])

In [6]:
t =([1,2,3],[4,5,6])
type(t)

tuple

In [7]:
k=np.array(t)

In [8]:
k.ndim

2

In [42]:
a=5
np.array(a)

array(5)

In [46]:
#deepv copy ans shallow copy in Numpy Array
l=[1,2,3,4,5]
arr = np.array(l)
arr

array([1, 2, 3, 4, 5])

In [47]:
arr[0]

1

In [48]:
arr[3]

4

In [49]:
a = arr

In [50]:
a

array([1, 2, 3, 4, 5])

In [51]:
arr[0] = 1000

In [52]:
arr

array([1000,    2,    3,    4,    5])

In [53]:
a

array([1000,    2,    3,    4,    5])

In [54]:
b=a.copy()

In [55]:
b

array([1000,    2,    3,    4,    5])

In [56]:
b[0] = 2000

In [57]:
b

array([2000,    2,    3,    4,    5])

In [58]:
a

array([1000,    2,    3,    4,    5])

In [59]:
#there are multiple ways to generating arrays

In [62]:
np.fromfunction(lambda i,j:i==j,(3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [63]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [65]:
arr

array([1000,    2,    3,    4,    5])

In [66]:
arr.shape

(5,)

In [67]:
arr1.shape#indicates 2 rows and 3 coloumns

(2, 3)

In [69]:
b=np.fromfunction(lambda i,j:i==j,(3,3))

In [70]:
b.shape#shapes gives us dimenstions

(3, 3)

In [71]:
arr1.size

6

In [72]:
b.size#no of elements

9

In [73]:
np.fromfunction(lambda i,j:i*j,(3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [75]:
for i in range(5):
    print(i)

0
1
2
3
4


In [76]:
l1=[i for i in range(5)]
l1

[0, 1, 2, 3, 4]

In [80]:
list(i for i in range(5))

[0, 1, 2, 3, 4]

In [81]:
[i for i in range(5)]

[0, 1, 2, 3, 4]

In [89]:
(i for i in range(5))

<generator object <genexpr> at 0x00000257B7F202B0>


In [85]:
{i for i in range(5)}

{0, 1, 2, 3, 4}

In [90]:
iterable = (i for i in range(5))

In [91]:
np.fromiter(iterable,float)

array([0., 1., 2., 3., 4.])

In [92]:
iterable =(i*i for i in range(5))

In [93]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [94]:
np.fromstring('23 34 67',sep =" ")

array([23., 34., 67.])

In [95]:
np.fromstring('23,34,67',sep =",")

array([23., 34., 67.])

In [96]:
np.fromstring("Suhani,Ajay,Anwesha",sep=',')


C:\Users\boras\AppData\Local\Temp\ipykernel_15732\2661167293.py:1: DeprecationWarning: string or file could not be read to its end due to unmatched data; this will raise a ValueError in the future.
  np.fromstring("Suhani,Ajay,Anwesha",sep=',')


array([], dtype=float64)

In [97]:
iterable = (i*i for i in range(5))
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [98]:
arr

array([1000,    2,    3,    4,    5])

In [99]:
arr.size

5

In [100]:
arr.shape

(5,)

In [102]:
arr.dtype

dtype('int32')

In [104]:
l = [1,2,3]
arr= np.array(l)

In [106]:
arr.dtype

dtype('int32')

In [107]:
l = [1,2,3,"Ajay"]
arr= np.array(l)

In [108]:
arr.dtype

dtype('<U11')

In [109]:
list(range(5))#here not getting all the values

[0, 1, 2, 3, 4]

In [110]:
range(5)

range(0, 5)

In [111]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [113]:
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [112]:
list(range(1.0,2.10))#range can not deal with float value

TypeError: 'float' object cannot be interpreted as an integer

In [116]:
list(np.arange(0.1,10.2,0.2))

[0.1,
 0.30000000000000004,
 0.5000000000000001,
 0.7000000000000001,
 0.9000000000000001,
 1.1000000000000003,
 1.3000000000000003,
 1.5000000000000004,
 1.7000000000000004,
 1.9000000000000004,
 2.1000000000000005,
 2.3000000000000007,
 2.5000000000000004,
 2.7000000000000006,
 2.900000000000001,
 3.1000000000000005,
 3.3000000000000007,
 3.500000000000001,
 3.7000000000000006,
 3.900000000000001,
 4.1000000000000005,
 4.300000000000001,
 4.500000000000001,
 4.7,
 4.9,
 5.1000000000000005,
 5.300000000000001,
 5.500000000000001,
 5.700000000000001,
 5.9,
 6.1000000000000005,
 6.300000000000001,
 6.500000000000001,
 6.700000000000001,
 6.900000000000001,
 7.100000000000001,
 7.300000000000001,
 7.500000000000001,
 7.700000000000001,
 7.900000000000001,
 8.100000000000001,
 8.3,
 8.500000000000002,
 8.700000000000001,
 8.900000000000002,
 9.100000000000001,
 9.3,
 9.500000000000002,
 9.700000000000001,
 9.900000000000002,
 10.100000000000001]

In [119]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [126]:
np.logspace(1,5,10,base=2)

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [127]:
np.logspace(1,5,10,base=10)

array([1.00000000e+01, 2.78255940e+01, 7.74263683e+01, 2.15443469e+02,
       5.99484250e+02, 1.66810054e+03, 4.64158883e+03, 1.29154967e+04,
       3.59381366e+04, 1.00000000e+05])

In [ ]:
#difference between logspace():-give at equidistance and linespace():-exact value

In [131]:
arr1=np.zeros(5)
arr1.shape

(5,)

In [132]:
arr2=np.zeros((3,4),int)
arr2.shape

(3, 4)

In [133]:
arr2

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [136]:
arr3 = np.zeros((3,3,4),int)
arr3.shape

(3, 3, 4)

In [137]:
arr3

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [138]:
arr3.size#two dimenstional array repeated 3 times ex:-(3,4),(3,4),(3,4)

36

In [143]:
arr4=np.zeros((4,3,4),int)
arr4.shape

(4, 3, 4)

In [144]:
arr4

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [146]:
np.ones(5,int)

array([1, 1, 1, 1, 1])

In [147]:
arr4.ndim

3

In [148]:
arr3.ndim

3

In [150]:
arr5=np.zeros((1,3,3,4),int)

In [152]:
arr5.ndim

4

In [153]:
arr5

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]])

In [156]:
arr=np.ones((3,4),int)

In [157]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [158]:
arr+5

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [159]:
arr*3

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [2]:
import numpy as np
help(np.sort)

Help on function sort in module numpy:

sort(a, axis=-1, kind=None, order=None)
    Return a sorted copy of an array.
    
    Parameters
    ----------
    a : array_like
        Array to be sorted.
    axis : int or None, optional
        Axis along which to sort. If None, the array is flattened before
        sorting. The default is -1, which sorts along the last axis.
    kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
        Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
        and 'mergesort' use timsort or radix sort under the covers and, in general,
        the actual implementation will vary with data type. The 'mergesort' option
        is retained for backwards compatibility.
    
        .. versionchanged:: 1.15.0.
           The 'stable' option was added.
    
    order : str or list of str, optional
        When `a` is an array with fields defined, this argument specifies
        which fields to compare first, second, etc.  A si