In [1]:
import numpy as np

In [2]:
data =np.array([[1],[2],[3]])

In [3]:
data

array([[1],
       [2],
       [3]])

In [4]:
data.shape

(3, 1)

In [5]:
data.ndim

2

In [6]:
a=np.squeeze(data)#use case:-reduce the dimension of data

In [7]:
a

array([1, 2, 3])

In [8]:
a.ndim

1

In [9]:
a.shape

(3,)

In [10]:
#repeat
data

array([[1],
       [2],
       [3]])

In [11]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [12]:
arr1=np.array([[1,2],[3,4]])

In [13]:
arr1

array([[1, 2],
       [3, 4]])

In [14]:
np.repeat(arr1,2)#reshape again its original position

array([1, 1, 2, 2, 3, 3, 4, 4])

In [15]:
#Ans:-
arr1.reshape(2,-1)

array([[1, 2],
       [3, 4]])

In [16]:
np.repeat(arr1,2,axis=1)

array([[1, 1, 2, 2],
       [3, 3, 4, 4]])

In [17]:
np.repeat(arr1,2,axis=0)

array([[1, 2],
       [1, 2],
       [3, 4],
       [3, 4]])

In [18]:
data

array([[1],
       [2],
       [3]])

In [19]:
np.roll(data,1)

array([[3],
       [1],
       [2]])

In [20]:
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [21]:
np.roll(data,3)

array([[1],
       [2],
       [3]])

In [22]:
np.roll(data,-1)

array([[2],
       [3],
       [1]])

In [23]:
np.roll(data,-2)

array([[3],
       [1],
       [2]])

In [24]:
np.roll(data,-3)

array([[1],
       [2],
       [3]])

In [25]:
np.diag(np.array([1,2,3,4,5]))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [26]:
a=np.array([[1,2],[3,4],[5,6]])

In [27]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [28]:
np.roll(a,1,axis=0)

array([[5, 6],
       [1, 2],
       [3, 4]])

In [29]:
np.roll(a,1,axis=1)

array([[2, 1],
       [4, 3],
       [6, 5]])

In [30]:
#Binary operation on array
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [31]:
arr1

array([[1, 1, 2, 9],
       [4, 2, 5, 3],
       [4, 1, 5, 3]])

In [32]:
arr2

array([[5, 2, 2, 2],
       [5, 2, 6, 2],
       [2, 7, 1, 6]])

In [33]:
arr1+arr2

array([[ 6,  3,  4, 11],
       [ 9,  4, 11,  5],
       [ 6,  8,  6,  9]])

In [34]:
arr1*arr2

array([[ 5,  2,  4, 18],
       [20,  4, 30,  6],
       [ 8,  7,  5, 18]])

In [35]:
arr1 / arr2

array([[0.2       , 0.5       , 1.        , 4.5       ],
       [0.8       , 1.        , 0.83333333, 1.5       ],
       [2.        , 0.14285714, 5.        , 0.5       ]])

In [36]:
arr1 - arr2

array([[-4, -1,  0,  7],
       [-1,  0, -1,  1],
       [ 2, -6,  4, -3]])

In [37]:
arr1 > arr2

array([[False, False, False,  True],
       [False, False, False,  True],
       [ True, False,  True, False]])

In [38]:
arr1 < arr2

array([[ True,  True, False, False],
       [ True, False,  True, False],
       [False,  True, False,  True]])

In [39]:
~arr1

array([[ -2,  -2,  -3, -10],
       [ -5,  -3,  -6,  -4],
       [ -5,  -2,  -6,  -4]])

In [40]:
arr1 ** arr2

array([[    1,     1,     4,    81],
       [ 1024,     4, 15625,     9],
       [   16,     1,     5,   729]])

In [41]:
#Numpy String Funtion
arr = np.array(['pw',"Skills"])

In [42]:
arr

array(['pw', 'Skills'], dtype='<U6')

In [43]:
np.char.upper(arr)

array(['PW', 'SKILLS'], dtype='<U6')

In [44]:
np.char.upper(np.array(["Ajay"]))

array(['AJAY'], dtype='<U4')

In [45]:
np.char.capitalize(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [46]:
np.char.title(arr)

array(['Pw', 'Skills'], dtype='<U6')

In [47]:
#mathematical function

arr1

array([[1, 1, 2, 9],
       [4, 2, 5, 3],
       [4, 1, 5, 3]])

In [48]:
np.sin(arr1)

array([[ 0.84147098,  0.84147098,  0.90929743,  0.41211849],
       [-0.7568025 ,  0.90929743, -0.95892427,  0.14112001],
       [-0.7568025 ,  0.84147098, -0.95892427,  0.14112001]])

In [49]:
np.cos(arr1)

array([[ 0.54030231,  0.54030231, -0.41614684, -0.91113026],
       [-0.65364362, -0.41614684,  0.28366219, -0.9899925 ],
       [-0.65364362,  0.54030231,  0.28366219, -0.9899925 ]])

In [50]:
np.tan(arr1)

array([[ 1.55740772,  1.55740772, -2.18503986, -0.45231566],
       [ 1.15782128, -2.18503986, -3.38051501, -0.14254654],
       [ 1.15782128,  1.55740772, -3.38051501, -0.14254654]])

In [51]:
np.log10(arr1)

array([[0.        , 0.        , 0.30103   , 0.95424251],
       [0.60205999, 0.30103   , 0.69897   , 0.47712125],
       [0.60205999, 0.        , 0.69897   , 0.47712125]])

In [52]:
np.exp(arr1)

array([[2.71828183e+00, 2.71828183e+00, 7.38905610e+00, 8.10308393e+03],
       [5.45981500e+01, 7.38905610e+00, 1.48413159e+02, 2.00855369e+01],
       [5.45981500e+01, 2.71828183e+00, 1.48413159e+02, 2.00855369e+01]])

In [53]:
np.power(arr1,3)

array([[  1,   1,   8, 729],
       [ 64,   8, 125,  27],
       [ 64,   1, 125,  27]], dtype=int32)

In [54]:
np.mean(arr1)

3.3333333333333335

In [55]:
np.max(arr1)

9

In [56]:
np.std(arr1)

2.2110831935702664

In [57]:
np.var(arr1)

4.888888888888888

In [58]:
np.max(arr1)

9

In [59]:
arr1 - arr2

array([[-4, -1,  0,  7],
       [-1,  0, -1,  1],
       [ 2, -6,  4, -3]])

In [60]:
np.subtract(arr1,arr2)

array([[-4, -1,  0,  7],
       [-1,  0, -1,  1],
       [ 2, -6,  4, -3]])

In [61]:
arr1 + arr2

array([[ 6,  3,  4, 11],
       [ 9,  4, 11,  5],
       [ 6,  8,  6,  9]])

In [62]:
np.multiply(arr1,arr2)

array([[ 5,  2,  4, 18],
       [20,  4, 30,  6],
       [ 8,  7,  5, 18]])

In [63]:
np.mod(arr1,arr2)#return element wise remainder

array([[1, 1, 0, 1],
       [4, 0, 5, 1],
       [0, 1, 0, 3]])

In [64]:
np.power(arr1,arr2)

array([[    1,     1,     4,    81],
       [ 1024,     4, 15625,     9],
       [   16,     1,     5,   729]])

In [65]:
np.sqrt(arr1)

array([[1.        , 1.        , 1.41421356, 3.        ],
       [2.        , 1.41421356, 2.23606798, 1.73205081],
       [2.        , 1.        , 2.23606798, 1.73205081]])

In [68]:
#Sort and Search
arr = np.array([5,6,1,2])
arr

array([5, 6, 1, 2])

In [69]:
np.sort(arr)

array([1, 2, 5, 6])

In [74]:
np.searchsorted(arr,3)#return index inserted at 3rd /index -1

4

In [75]:
arr =np.array([0,1,2,3,0,4])
np.count_nonzero(arr)

4

In [77]:
arr > 0

array([False,  True,  True,  True, False,  True])

In [79]:
np.where(arr>0)

(array([1, 2, 3, 5], dtype=int64),)

In [82]:
np.extract(arr > 0 ,arr)#returns array

array([1, 2, 3, 4])

In [83]:
arr1=np.array([5,6,1,2,8,9])

In [85]:
np.sort(arr1)

array([1, 2, 5, 6, 8, 9])

In [84]:
np.searchsorted(arr1,7)

4

In [86]:
arr=np.array([5,6,100,200,1,2,8,9])

In [87]:
arr

array([  5,   6, 100, 200,   1,   2,   8,   9])

In [92]:
np.searchsorted(arr,3)

6

In [95]:
arr1=np.array([0,1,2,3,0,4])

In [96]:
arr1

array([0, 1, 2, 3, 0, 4])

In [97]:
arr1.byteswap()

array([       0, 16777216, 33554432, 50331648,        0, 67108864])

In [98]:
#matrix>>2d array

In [99]:
import numpy.matlib as nm #matlib-matrix labriry

In [100]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [102]:
nm.ones((3,4),int)

matrix([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [103]:
#Numpy linear algebra

In [104]:
arr1=np.random.randint(1,10,(3,4))
arr2=np.random.randint(1,10,(3,4))

In [107]:
arr1=np.array([[2,3],[4,5]])
arr2=np.array([[1,3],[4,5]])

In [110]:
arr1

array([[2, 3],
       [4, 5]])

In [109]:
arr2

array([[1, 3],
       [4, 5]])

In [111]:
arr1 @ arr2

array([[14, 21],
       [24, 37]])

In [ ]:
#7x+5y-3z=16
#2x-5y+2z=-8
#5x+3y-7z=0

In [117]:
a=np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [118]:
a

array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [119]:
b=np.array([16,-8,0])

In [120]:
b

array([16, -8,  0])

In [121]:
np.linalg.solve(a,b)

array([0.90162081, 2.89483603, 1.88465888])

In [122]:
arr1

array([[2, 3],
       [4, 5]])

In [123]:
5*2 - 3*4#determinanant

-2

In [124]:
np.linalg.det(arr1)

-2.0

In [125]:
np.linalg.inv(arr1)

array([[-2.5,  1.5],
       [ 2. , -1. ]])